// packages/create-sst/bin/presets/examples/svelte-app/templates/packages/frontend/src/App.svelte
<script>
let count = 0;

function onClick() {
	fetch(import.meta.env.VITE_APP_API_URL, {
		method: "POST",
	})
		.then((response) => response.text())
		.then((data) => {
			count = data;
		});
}
</script>

<div class="App">
  <div>
    <p>You clicked me {count} times.</p>
    <button on:click={onClick}>Click Me!</button>
  </div>
</div>


<style>
  .App {
    height: 100vh;
    display: grid;
    text-align: center;
    place-items: center;
  }
  p {
    margin-top: 0;
    font-size: 20px;
  }
  button {
    font-size: 48px;
  }
</style>

// packages/create-sst/bin/presets/examples/react-app/templates/packages/frontend/src/App.js
import { useState } from "react";
import "./App.css";

export default function App() {
	const [count, setCount] = useState(null);

	function onClick() {
		fetch(process.env.REACT_APP_API_URL, {
			method: "POST",
		})
			.then((response) => response.text())
			.then(setCount);
	}

	return (
		<div className="App">
			{count && <p>You clicked me {count} times.</p>}
			<button onClick={onClick}>Click Me!</button>
		</div>
	);
}
