// packages/create-sst/bin/presets/examples/svelte-app/templates/packages/frontend/src/App.svelte
<script>
let count = 0;

function onClick() {
	fetch(import.meta.env.VITE_APP_API_URL, {
		method: "POST",
	})
		.then((response) => response.text())
		.then((data) => {
			count = data;
		});
}
</script>

<div class="App">
  <div>
    <p>You clicked me {count} times.</p>
    <button on:click={onClick}>Click Me!</button>
  </div>
</div>


<style>
  .App {
    height: 100vh;
    display: grid;
    text-align: center;
    place-items: center;
  }
  p {
    margin-top: 0;
    font-size: 20px;
  }
  button {
    font-size: 48px;
  }
</style>

// packages/create-sst/bin/presets/examples/quickstart-standalone/templates/packages/web/src/App.tsx
import { useState } from "react";
import "./App.css";

function App() {
	const [message, setMessage] = useState("Hi 👋");

	function onClick() {
		fetch(import.meta.env.VITE_APP_API_URL)
			.then((response) => response.text())
			.then(setMessage);
	}

	return (
		<div className="App">
			<div className="card">
				<button onClick={onClick}>
					Message is "<i>{message}</i>"
				</button>
			</div>
		</div>
	);
}

export default App;
