// packages/create-sst/bin/presets/examples/quickstart-sveltekit/templates/src/routes/+page.svelte
<script lang="ts">
import type { PageData } from "./$types";

export let data: PageData;

const handleSubmit = async (e: SubmitEvent) => {
	const formData = new FormData(e.target as HTMLFormElement);
	const file = formData.get("file") as File;

	const image = await fetch(data.url, {
		body: file,
		method: "PUT",
		headers: {
			"Content-Type": file.type,
			"Content-Disposition": `attachment; filename="${file.name}"`,
		},
	});

	window.location.href = image.url.split("?")[0];
};
</script>

<svelte:head>
  <title>Home</title>
  <meta name="description" content="Svelte demo app" />
</svelte:head>

<section>
  <form on:submit|preventDefault={handleSubmit}>
    <input name="file" type="file" accept="image/png, image/jpeg" />
    <button type="submit">Upload</button>
  </form>
</section>

<style>
  section {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    flex: 0.6;
  }
</style>

// packages/create-sst/bin/presets/examples/quickstart-solidstart/templates/src/routes/index.tsx
import crypto from "crypto";
import { PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { useRouteData } from "solid-start";
import { createServerData$ } from "solid-start/server";
import { Bucket } from "sst/node/bucket";

export function routeData() {
	return createServerData$(async () => {
		const command = new PutObjectCommand({
			ACL: "public-read",
			Key: crypto.randomUUID(),
			Bucket: Bucket.public.bucketName,
		});
		return await getSignedUrl(new S3Client({}), command);
	});
}

export default function Home() {
	const url = useRouteData<typeof routeData>();

	return (
		<main>
			<h1>Hello world!</h1>
			<form
				onSubmit={async (e) => {
					e.preventDefault();

					const file = (e.target as HTMLFormElement).file.files?.[0]!;

					const image = await fetch(url() as string, {
						body: file,
						method: "PUT",
						headers: {
							"Content-Type": file.type,
							"Content-Disposition": `attachment; filename="${file.name}"`,
						},
					});

					window.location.href = image.url.split("?")[0];
				}}
			>
				<input name="file" type="file" accept="image/png, image/jpeg" />
				<button type="submit">Upload</button>
			</form>
		</main>
	);
}
